--> NuiTerm/Term.lua
--
local Setup = require("NuiTerm.setup")
local Utils = require("NuiTerm.utils")
local Debug = require("NuiTerm.Debug")
local Keymaps = require("NuiTerm.Keymap.Term")
local fn, api, map = vim.fn, vim.api, vim.keymap.set

local AUGROUP = api.nvim_create_augroup("NuiTermHover", { clear = true })

local log = Debug.LOG_FN("TermWindow", {
  deactivate = true,
})

---@class TermWindow
---@field bufnr       number|nil
---@field winid       number|nil
---@field termid      number|nil
---@field name        string
---@field autocmdid   number|nil
---@field config      table
---@field onHide      function|nil
---@field showing     boolean
---@field spawned     boolean
---@field initialized boolean
local TermWindow = {
  ---@typw bufnr = number
  bufnr       = nil,
  winid       = nil,
  termid      = nil,
  name        = "Terminal",
  autocmdid   = nil,
  config      = {},
  onHide      = nil,
  showing     = false,
  spawned     = false,
  initialized = false,
  originalMouse = "",
}

function TermWindow:IsBufValid()
  local valid = self.bufnr and api.nvim_buf_is_valid(self.bufnr)
  if not valid then
    log("Bufnr was somehow deleted!", "IsBufValid")
  end
  return valid
end

-- Function to Create a new Termianl Instance
-- @param termid number: The Terminal's ID
-- @param width number: The width of the terminal window
-- @param height number: The height of the terminal window
-- @param col number: The X coordinate for the floating window
-- @param row number: The Y coordinate for the floating window
function TermWindow:Init(termid, config)
  local obj = setmetatable({}, { __index = self })
  obj.termid = termid
  obj.config = config
  local bufnr = vim.api.nvim_create_buf(false, true)
  vim.bo[bufnr].bufhidden  = "hide"
  vim.bo[bufnr].buftype    = "acwrite"
  vim.bo[bufnr].modifiable = false
  obj.originalMouse = vim.o.mouse
  obj.bufnr = bufnr
  obj.initialized = true
  obj.spawned = false
  Utils.PreventFileOpenInTerm(obj.bufnr)
  return obj
end

function TermWindow:OnHoverOver(current)
  if current.screenrow >= self.config.row
    and current.screenrow <= self.config.row + self.config.height
  then
    api.nvim_exec_autocmds("User", { pattern = "NuiTermHoverOver" })
    log("Hover Pos: x: " .. current.screencol .. " y: " .. current.screenrow)
  else
    api.nvim_exec_autocmds("User", { pattern = "NuiTermHoverOut" })
    log("NotHovering Over NuiTerm")
  end
end

function TermWindow:RecreateBuf()
  if not self:IsBufValid() then
    local bufnr = api.nvim_create_buf(false, true)
    vim.bo[bufnr].bufhidden = 'wipe'
    self.bufnr = bufnr
    self.spawned = false
  end
end

function TermWindow:SpawnShell(onLeave)
  -- print("TermWIndow:SpawnShell " .. self.termid)
  -- print("BUFNR: " .. self.bufnr)
  if self.spawned then
    log("Already spawned ID: " .. self.termid, "SpawnShell")
    return
  end
  -- vim.cmd("terminal")
  vim.fn.termopen(vim.o.shell, {
    bufnr = self.bufnr,
    on_exit = function()
      log("ON_EXIT!", "SpawnShell")
      onLeave()
    end,
  })
  self.spawned = true
end

-- Creats a new Floating window, with the specified window confiurations originally passed
-- to this TermWindow instance wihtin Init
-- returns the window ID generated by nvim_open_win
function TermWindow:Show(onLeave)
  self:RecreateBuf()
  if not self.config then
    error("TermWindow:Show(): Self.config is nil", 2)
  end
  local winid = api.nvim_open_win(self.bufnr, true, self.config)
  self.winid  = winid
  self.onHide = onLeave
  self:SpawnShell(onLeave)
  self.showing = true;
  Keymaps.CreateTermKeyMaps(self.bufnr)
  return winid
end

function TermWindow:Hide()
  if not self.winid or not api.nvim_win_is_valid(self.winid) then
    return
  end

  Keymaps.RemoveTermKeymaps(self.bufnr)

  self.showing = false;
  api.nvim_win_hide(self.winid)
  self.winid = nil
end

function TermWindow:Delete()
  self:Hide()
  self.bufnr = nil
  self.termid = nil
end

---@param config table
function TermWindow:UpdateConfig(config)
  self.config = config
end



return {
  TermWindow = TermWindow,
}
